### ISSUE TITLE
Specific image requirements

### ISSUE THREAD

**Issue by drsanjayrana** [mzucker/maptrace#1]
Hi, 

This looks quite impressive but I can't seem to be able to get it to work for any image other than your examples.  
[Parts.90_boundaries_outer.zip](https://github.com/mzucker/maptrace/files/3124701/Parts.90_boundaries_outer.zip). For the cases where it does work, the output looks quite different to the image. I was wondering if the input data has to be of a certain format, colour etc.

error trace for my own image as below:

python maptrace.py -c Parts.90_boundaries_outer.tif

found 0 labels
computing areas... Traceback (most recent call last):
  File "maptrace.py", line 1109, in <module>
    main()
  File "maptrace.py", line 1094, in main
    num_labels, labels, slices, colors = get_labels_and_colors(mask, opts)
  File "maptrace.py", line 625, in get_labels_and_colors
    areas, bins = np.histogram(labels.flatten(), bins=num_labels, range=(1, num_labels + 1))
  File "C:\Anaconda3\lib\site-packages\numpy\lib\function_base.py", line 721, in histogram
    raise ValueError('`bins` must be positive, when an integer')
ValueError: `bins` must be positive, when an integer

Sanjay.

**Comment by RRYontz** [comment]
My initial guess, since your source image is a 24MB tiff, is that it is a "MULTI-MEGAPIXEL IMAGE" (see 3rd bullet in the README.md file) and not supported. I too am wanting to trace a multi-megapixel image and am hopeful that after studying this for a bit, I might be able to find a way to apply this to the larger images. I am not worried about the speed at the moment, but need a good automated tool to process batch scans of engineering plans.
